stages:
  - test
  - deploy

backend-core-test:
  image: node:8.10
  stage: test
  before_script:
    - cd backend-core
  script:
    - npm install
    - npm run test
  when: manual

web-test:
  image: node:8.10
  stage: test
  before_script:
    - cd web
  script:
    - npm install
    - npm run test
  when: manual

backend-core-deploy:
  image: fadhlanhazmi/heroku-deploy:latest
  stage: deploy
  before_script:
    - cd backend-core
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
  when: manual

web-deploy:
  image: fadhlanhazmi/heroku-deploy:latest
  stage: deploy
  before_script:
    - cd web
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME_ADMIN --api-key=$HEROKU_APIKEY
  when: manual

websocket-deploy:
  image: fadhlanhazmi/heroku-deploy:latest
  stage: deploy
  before_script:
    - cd websocket
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME_WS --api-key=$HEROKU_APIKEY
  when: manual