package id.ac.ui.cs.mobileprogramming.ilham_darmawan.konselink_counselor.model.retrofit

class ClientDetail(
    var name: String? = null,
    var gender: String? = null,
    var birthPlace: String? = null,
    var birthDay: Int? = null,
    var birthMonth: Int? = null,
    var birthYear: Int? = null,
    var age: Int? = null,
    var religion: String? = null,
    var address: String? = null,
    var phoneNumber: String? = null,
    var email: String? = null,
    var currentEducation: String? = null,
    var currentProfession: String? = null,
    var hasConsultedBefore: Boolean? = null,
    var monthConsulted: Int? = null,
    var yearConsulted: Int? = null,
    var placeConsulted: String? = null,
    var complaint: String? = null,
    var solution: String? = null,
    var problem: String? = null,
    var effortDone: String? = null,
    var kindergartenData: String? = null,
    var elementaryData: String? = null,
    var juniorData: String? = null,
    var seniorData: String? = null,
    var collegeData: String? = null,
    var kindergartenDataParsed: List<EducationData>? = null,
    var elementaryDataParsed: List<EducationData>? = null,
    var juniorDataParsed: List<EducationData>? = null,
    var seniorDataParsed: List<EducationData>? = null,
    var collegeDataParsed: List<EducationData>? = null,

    var fatherName: String? = null,
    var fatherAge: Int? = null,
    var fatherReligion: String? = null,
    var fatherTribe: String? = null,
    var fatherEducation: String? = null,
    var fatherOccupation: String? = null,
    var fatherAddress: String? = null,

    var motherName: String? = null,
    var motherAge: Int? = null,
    var motherReligion: String? = null,
    var motherTribe: String? = null,
    var motherEducation: String? = null,
    var motherOccupation: String? = null,
    var motherAddress: String? = null,

    var sibling1Name: String? = null,
    var sibling1Gender: String? = null,
    var sibling1Age: Int? = null,
    var sibling1Education: String? = null,

    var sibling2Name: String? = null,
    var sibling2Gender: String? = null,
    var sibling2Age: Int? = null,
    var sibling2Education: String? = null,

    var sibling3Name: String? = null,
    var sibling3Gender: String? = null,
    var sibling3Age: Int? = null,
    var sibling3Education: String? = null,

    var sibling4Name: String? = null,
    var sibling4Gender: String? = null,
    var sibling4Age: Int? = null,
    var sibling4Education: String? = null,

    var sibling5Name: String? = null,
    var sibling5Gender: String? = null,
    var sibling5Age: Int? = null,
    var sibling5Education: String? = null
)